
env:
  - LOCAL_REPOS_HOST=172.17.0.2
  - PIP_OPTS="--index-url=http://${LOCAL_REPOS_HOST}/repo/pypi/simple/ --trusted-host=${LOCAL_REPOS_HOST}"

docker-images:
  python:2.7: ownport/python-dev:2.7

docker-opts:
  name: jltools-dev-local-ci
  hostname: jltools-dev-local-ci
